### ISSUE TITLE
Fixed hex value issue - Make the hex generated by the function dynamic

### ISSUE THREAD

**Issue by umairian** [UmairJibran/random-hex#1]
@UmairJibran , I have been through the code but I found that the hex generated is only limited to six digits. You can't change it. It would be a good fix to take the number of digits as input in the function and generate hex having number of digits equal to that input number.

**Comment by UmairJibran** [comment]
oh yes, that is great input, I would gladly add that, although because of missing information, I did not convey that this was for creating a hex code for colours 😄

It's added
